
import "./globals.css";
import Nav from "./components/Nav";

export const metadata = {
  title: "Evoxcel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
